### ISSUE TITLE
Documentation how to call the main algorithms

### ISSUE THREAD

**Issue by zuphilip** [infolis/infolis.github.io#13]
I would appreciate some documentation how to call the main algorithms through the API's `execute`. At the moment I only managed to call the `TextExtractor` algorithm successfully.

Which algorithm expect which parameters and should they be text strings, ids or full written uris? Maybe some example calls helps as well.

**Comment by kba** [comment]
See also https://github.com/infolis/infolis-web/issues/10

**Comment by zuphilip** [comment]
I began documenting some calls for the main algorithm: https://github.com/infolis/infolis-web/wiki/API-calls-to-algorithms , however I am not familiar with the details. Thus any help is welcome to expand this information.

**Comment by zuphilip** [comment]
That has worked out pretty well, many thanks to all contributors of the wiki page. I will close the issue here now. However, more documentation is always appreciated.
