### ISSUE TITLE
Documentation for RESTful API in Swagger interface

### ISSUE THREAD

**Issue by LetschM** [infolis/infolis.github.io#15]
Short documentation for the methods in the api to explain what they actually do. Users new to the project may not know anything about the functionalities at all.

**Comment by LetschM** [comment]
additionally short information for textboxes about what users have to fill in. E.g. what value is expected for Parameter "q" in several methods?

**Comment by kba** [comment]
Let's track this in https://github.com/infolis/infolis-web/issues/8 and https://github.com/infolis/infolis.github.io/issues/13. Contributions to https://github.com/infolis/infolis-web/wiki/API-calls-to-algorithms are much appreciated.
