### ISSUE TITLE
Startpage: Links are blue-on-blue

### ISSUE THREAD

**Issue by kba** [infolis/infolis.github.io#19]
![](http://i.imgur.com/Gg1nN2z.png)

I'll happily integrate good proposals for the `color` rules for these links.

**Comment by LetschM** [comment]
![links](https://cloud.githubusercontent.com/assets/6389153/11474191/d2544ef4-9776-11e5-88ab-9fa9655223ce.png)
Option 1: links in green (#96e089) or orange (#ffba6f)?

**Comment by LetschM** [comment]
Additionally increase opacity of underlying blue div for more contrast: e.g. from rgba(..., ..., ..., 0.7) to 0.9.

**Comment by LetschM** [comment]
![links2](https://cloud.githubusercontent.com/assets/6389153/11474600/5ac30116-9779-11e5-808e-c86113a2b4ca.png)
