### ISSUE TITLE
Include Twitter Timeline in Blog

### ISSUE THREAD

**Issue by zuphilip** [infolis/infolis.github.io#4]
We could include our twitter timeline on the blog page, e.g.

![blog-with-twitter](https://cloud.githubusercontent.com/assets/5199995/11170531/78ac5f54-8bd7-11e5-99f3-7ff3c45a4532.gif)

What do you think, should we do that? (Layout in the picture is 1-7-3-1 for the space, blog, twitter, space). The twitter widget I created in our account is the following

```
<a class="twitter-timeline" href="https://twitter.com/infolis_project" data-widget-id="665970218917896194">Tweets von @infolis_project </a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
```

**Comment by kba** [comment]
Sure, looks good. Thanks.
