### ISSUE TITLE
Add newest blog post to page

### ISSUE THREAD

**Issue by zuphilip** [infolis/infolis.github.io#7]
I would suggest to add the (most recent) blog posts back to the main page, which is otherwise quite empty, i.e. something like

![page](https://cloud.githubusercontent.com/assets/5199995/11171499/f4202d68-8bf1-11e5-9cb0-fc5f7e6b9f55.jpg)

However, the seperate icon (Read our Blog) is then maybe not needed anymore and can be linked directly.

**Comment by kba** [comment]
https://github.com/infolis/infolis.github.io/commit/a85be198f4267a620389ec6182f5892c9ca34863
