### ISSUE TITLE
Swagger JSON is not valid

### ISSUE THREAD

**Issue by LetschM** [infolis/infolis.github.io#8]
API is invalid:

[{"level":"error","domain":"validation","keyword":"oneOf","message":"instance failed to match exactly one schema (matched 0 out of 2)","schema":{"loadingURI":"http://swagger.io/v2/schema.json#","pointer":"/definitions/parametersList/items"},"instance":{"pointer":"/paths/~1api~1syntax-highlight/post/parameters/0"}}]

**Comment by zuphilip** [comment]
Is there still a problem?
